// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/entities": {
    params: {};
  };
  "/import": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/*" | "/entities" | "/import";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/entities._index.tsx": {
    id: "routes/entities._index";
    page: "/entities";
  };
  "routes/import._index.tsx": {
    id: "routes/import._index";
    page: "/import";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/entities._index": typeof import("./app/routes/entities._index.tsx");
  "routes/import._index": typeof import("./app/routes/import._index.tsx");
};